//-----------------------------------------------------------------------------
// Copyright (c) 2024 Electronic Arts.  All rights reserved.
//-----------------------------------------------------------------------------

// Code-generated by UniformBufferFactory
//!insert SimConstants

// const values like SolverTypeExplicit etc
// that are plugged in from js 
//!insert SimEnums

fn gridVertexIndex(gridVertex : vec2u, gridSize : vec2u) -> u32
{
    // Currently using lexicographical ordering
    // 4 components per grid vertex
    return u32(4*(gridVertex.y * gridSize.x + gridVertex.x));
}

fn decodeFixedPoint(fixedPoint : i32, fixedPointMultiplier : u32) -> f32
{
    return f32(fixedPoint) / f32(fixedPointMultiplier);
}

fn encodeFixedPoint(floatingPoint : f32, fixedPointMultiplier: u32) -> i32
{
    return i32(floatingPoint * f32(fixedPointMultiplier));
}
